package in.guardianservices.log_monitor_sdk.analyzer;

import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.core.AppenderBase;
import in.guardianservices.log_monitor_sdk.dto.LogAnalysisRequest;
import in.guardianservices.log_monitor_sdk.kafka.KafkaLogProducer;
import in.guardianservices.log_monitor_sdk.utils.LogEventMapper;

/**
 * A custom Logback Appender that intercepts application log events and publishes them to a Kafka topic.
 * Specifically, this appender filters and transmits only ERROR level log events to reduce
 * overhead and ensure fast throughput of critical application exceptions.
 */
public class KafkaAiLogAppender extends AppenderBase<ILoggingEvent> {

    private String bootstrapServers;
    private String topic;
    private KafkaLogProducer kafkaProducer;

    private String environment; // Added field
    private String serviceName; // New field

    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }
    public void setEnvironment(String environment) {
        this.environment = environment;
    }

    /**
     * Initializes the appender by creating an instance of the {@link KafkaLogProducer}.
     * This method is invoked by the Logback framework when the appender is started.
     */
    @Override
    public void start() {
        try {
            this.kafkaProducer = new KafkaLogProducer(bootstrapServers, topic);
            super.start();
        } catch (Exception e) {
            addError("Failed to initialize Kafka producer for AI Logging", e);
        }
    }

    /**
     * Processes individual log events intercepted by Logback.
     * This implementation checks if the incoming log event is an ERROR level or above,
     * serializes the event to JSON, and sends it using the Kafka producer.
     *
     * @param event The log event generated by the application.
     */
    @Override
    protected void append(ILoggingEvent event) {
        // Only process Error logs to maintain efficiency
        if (event.getLevel().isGreaterOrEqual(ch.qos.logback.classic.Level.ERROR)) {
            try {
//                String jsonPayload = LogEventMapper.toJson(event, this.environment);
                String logAnalysisRequest = LogEventMapper.mapLogEvent(event, this.environment, this.serviceName);

                kafkaProducer.sendLog(event.getLoggerName(), logAnalysisRequest);
            } catch (Exception e) {
                addError("Failed to map or send log to Kafka", e);
            }
        }
    }

    /**
     * Closes the Kafka producer and stops the appender.
     * This method is invoked by the Logback framework during shutdown to ensure resources are cleaned up.
     */
    @Override
    public void stop() {
        if (kafkaProducer != null) {
            kafkaProducer.close();
        }
        super.stop();
    }

    /**
     * Sets the Kafka bootstrap servers property. This is injected via the logback.xml configuration.
     *
     * @param s A comma-separated list of host:port configurations for the Kafka cluster.
     */
    public void setBootstrapServers(String s) { this.bootstrapServers = s; }

    /**
     * Sets the target Kafka topic where logs will be sent. This is injected via the logback.xml configuration.
     *
     * @param t The name of the Kafka topic.
     */
    public void setTopic(String t) { this.topic = t; }
}
